# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftStudy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftStudy
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'RxSwiftStudyTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
  end

  target 'RxSwiftStudyUITests' do
    # Pods for testing
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
  end

end
